language: node_js
sudo: required
dist: trusty
node_js:
  - "10"

cache:
  directories:
    - node_modules  

env:
  global:
    - DROPBOX_TOKEN=${DROPBOX_TOKEN}
    - CXX=g++-4.8
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default

before_script:
  - npm install
  - cp sample.env .env
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 #wait a while before xvfb to start

script:
  - npm run test
  - npm run upload

notifications:
  email: false